services:
  vault:
    image: vyary/vault-arm:latest
    ports:
      - "8080:8080"
      - "443:443"
    secrets:
      - port
      - db-url
      - db-auth
    environment:
      PORT: ${PORT:-port}
      DB_URL: ${DB_URL:-default_url}
      DB_AUTH_TOKEN: ${DB_AUTH_TOKEN:-default_auth_token}
      PROXY_TARGET: "http://localhost:8080"
      CERT_FILE: "/app/certs/cert.pem"
      KEY_FILE: "/app/certs/key.pem"
    volumes:
      - ./certs:/app/certs:ro 

secrets:
  port:
    external: true
  db-url:
    external: true
  db-auth:
    external: true
