services:
  vault:
    image: vyary/vault:latest
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - port
      - db-url
      - db-auth
    environment:
      PORT: ${PORT:-port}
      DB_URL: ${DB_URL:-default_url}
      DB_AUTH_TOKEN: ${DB_AUTH_TOKEN:-default_auth_token}
      PROXY_TARGET: "http://localhost:8080"
      CERT_FILE: "/etc/letsencrypt/live/eu.exile-profit.com/fullchain.pem"
      KEY_FILE: "/etc/letsencrypt/live/eu.exile-profit.com/privkey.pem"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

secrets:
  port:
    external: true
  db-url:
    external: true
  db-auth:
    external: true
